### PR TITLE
updated kangapost

### PR DESCRIPTION
**Pull request by javintfwong**
-added my version of kangapost with collisions (kept the old one there just in case, if not needed anymore just delete)
-added what ive done so far with the tileset
-getting used to git again xd

### CODE REVIEW

**Comment by jameshahaha** [comment]
just remove the old version from the assets folder and rename this one to `kangapost.png` then we're good to merge 👍

**Comment by jameshahaha** [comment]
collisions need to be adjusted a bit

image

player needs to be be able to walk below the counter and through some of these areas, can you take a look at the old kangapost collisions for reference? 

current: 
image

old:
image

e.g) there's no collisions boxes on the bottom tile of the tables for example, and as well as the boxes so that the player can actually walk there like this:

image
image

**Comment by javintfwong** [comment]
fixed da collision areas, should be good to go now

**Comment by jameshahaha** [comment]
closing for now and will redo collisions on `main` after map changes!

**Pull request closed without merging**
